### PR TITLE
fix docker ci

### PR DESCRIPTION
**Pull request by niqdev**
this is causing troubles `--mount=source=.git,target=.git,type=bind`, as far as i understood it's needed for the `-e` flag, but i never seen it before in a docker file

see
* https://github.com/pypa/setuptools-scm/issues/77
* https://github.com/nicolabs/nicobot/issues/53

### CODE REVIEW

**Comment by valerino** [comment]
yep, this is what i was actually trying to fix in fixin-docker branch before :)
the point is i am/was a total noob in docker and devops stuff, and i attempted to create a dockerfile myself, that's the result.

you can remove the mount things (they were needed also for private repositories we don't need anymore).
but, it will not work due to setuptools-scm not being able to calculate the version number anymore without .git.

help :)

**Comment by niqdev** [comment]
yup, i'll park this for now and check it out when i get a chance, this is the actual error
```
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 2zkxrekh56t3p7obuwarkpc1a::0wpue5n9a2ffovb4w5wle5ms4: "/.git": not found
```
Please let me knot if you find out first, thanks

**Comment by niqdev** [comment]
i think the only blocking dependencies is `muty-python`, right? I haven't published any dependencies on PyPI, but maybe if you do that this issue will go automatically away. wdyt?
This should do it https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

**Comment by valerino** [comment]
i think i mostly sorted out everything on fixing-docker branch. we are reviewing it (you're welcome, too!) and we will merge it later.

**Comment by niqdev** [comment]
sorry for the late reply but I was AFK, I'll check it out as soon as I can! thanks

**Pull request closed without merging**
